#!/bin/bash

sudo pacman -S --needed gtk3 cairo gtk-layer-shell libgirepository gobject-introspection gobject-introspection-runtime python python-pip python-gobject python-cairo python-loguru pkgconf
sudo pacman -S --needed wofi waybar
sudo pacman -S --needed kitty hyprland hyprpaper
yay -S python-fabric-git
