#!/bin/sh

autorandr --change
xmodmap ~/.config/X11/xmodmap
picom -f --vsync -o=0 &
nitrogen --restore

# a good place to put this i think
~/personal/deck/cdeck.py &

# Twas too broken
# ~/personal/handies/handwp.py &

# switch same does all the heavy lifting
~/.bin/switch same &

exec qtile start
