#!/bin/sh

autorandr --change
xmodmap ~/.config/X11/xmodmap
picom -f --vsync -o=0 &
nitrogen --restore &
dunst &
eww daemon &
eww open vertical &

# a good place to put these i think
# Twas too broken
# ~/personal/deck/cdeck.py &
# ~/personal/handies/handwp.py &

# `switch same` does the heavy lifting
~/.bin/switch same &

source ~/.config/X11/XDG_ENV

exec qtile start
