#!/bin/sh

source ~/.config/X11/xenv

autorandr --change
xmodmap ~/.config/X11/xmodmap
picom -f --vsync -o=0 &
nitrogen --restore &
dunst &
eww daemon &

# a good place to put these i think
# Twas too broken
# ~/personal/deck/cdeck.py &
# ~/personal/handies/handwp.py &

# `switch same` does the heavy lifting
# bad practice with not running in bg but bad practices can kiss my ass
~/.bin/switch same

exec qtile start
