#!/usr/bin/env bash

# Wasted 1 hour for it to be useless
# echo "$(zellij ls | awk '{print $1}' | sed 's/\[32;1//g' | sed 's/\[m//g' | sort -r | fzf)"

PROJ_FOLDERS=`echo ~/git ~/Projects ~/dots ~/dots/.config ~/test`
EXTR_FOLDERS=`echo ~/ ~/dots ~/git ~/test /etc`

if [[ -n $1 ]] then
  selected=$1
else
  selected=`find $PROJ_FOLDERS -maxdepth 1 -mindepth 1 -type d | cat - <(echo $EXTR_FOLDERS) | sed 's/ /\n/g' | sort -r | fzf --tmux top,70%,45% --preview "ls -A {}"`
fi

if [[ -z $selected ]] then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
