#!/bin/bash

CURRENT=`cat $QTILE_THEME_HOME/.colorscheme`

if [[ -z $1 ]] then
  case $CURRENT in
    "latte" ) NEW="frappe" ;;
    "frappe") NEW="latte"  ;;
    *       ) NEW="frappe" ;;
  esac
else
  if [[ "$1" == "frappe" || "$1" == "latte" ]] then
    NEW=$1
  elif [[ "$1" == "same" ]] then
    NEW=$CURRENT
  else
    echo No such theme
    echo Themes: frappe, latte
    echo Or use \`same\` to reload/strap the current theme
    exit
  fi
fi

echo Switching to $NEW theme 
echo $NEW > $QTILE_THEME_HOME/.colorscheme

echo Refreshing polybar...
echo -en "[colors]\ninclude-file = $HOME/.config/polybar/themes/$NEW.ini" > $HOME/.config/polybar/themes/current.ini
$HOME/.config/polybar/startup.sh >/dev/null 2>/dev/null

sleep 1

# echo Setting wallpaper...
# WPFILE=`ls $HOME/wps/$NEW | sort | head -n 1`
# nitrogen --set-auto $HOME/wps/$NEW/$WPFILE >/dev/null 2>/dev/null

echo Refreshing qtile...
pkill -SIGUSR1 qtile

echo Themeing nvim...
pkill -SIGUSR1 nvim

echo Themeing kitty...
# Also setting stuff for next steps. opps
case "$NEW" in
  "latte")
    kitten theme catppuccin-latte 
    VENCORD='@import url("https://catppuccin.github.io/discord/dist/catppuccin-latte.theme.css");'
    ;;
  "frappe" )
    kitten theme catppuccin-frappe
    VENCORD='@import url("https://catppuccin.github.io/discord/dist/catppuccin-frappe-lavender.theme.css");'
    ;;
esac

pkill -SIGUSR1 kitty

echo Themeing spotify...
spicetify config current_theme catppuccin -q
spicetify config color_scheme $NEW -q
spicetify config inject_css 1 inject_theme_js 1 replace_colors 1 overwrite_assets 1 -q
spicetify apply -q

echo Themeing discord...
echo $VENCORD > $HOME/.config/Vencord/themes/catppuccin-dynamic.css 

echo Themeing eww...
echo "@import '$HOME/.themes/catppuccin/scss/$NEW';" > $HOME/.config/eww/_current.scss

$HOME/.bin/myeww same

# echo Thememing streamdeck
# pkill -SIGUSR1 cdeck 
