#!/bin/bash

CURRENT=`cat $HOME/.colorscheme`

if [[ -z $1 ]] then
  case $CURRENT in
    "latte") NEW="frappe" ;;
    "frappe" ) NEW="latte" ;;
    *      ) NEW="frappe" ;;
  esac
else
  if [[ "$1" == "frappe" || "$1" == "latte" ]] then
    NEW=$1
  elif [[ "$1" == "same" ]] then
    NEW=$CURRENT
  else
    echo No such theme
    echo Themes: frappe, latte
    echo Or use \`same\` to reload/strap the current theme
    exit
  fi
fi

echo Switching to $NEW theme 
echo $NEW > $HOME/.colorscheme

killall -q polybar
killall -q eww

if [[ -n $2 ]] then
  BAR=$2
else
  BAR="polybar"
fi

case "$BAR" in
  "polybar")
    echo Refreshing polybar...
    echo -en "[colors]\ninclude-file = $HOME/.config/polybar/themes/$NEW.ini" > $HOME/.config/polybar/themes/current.ini
    $HOME/.config/polybar/startup.sh >/dev/null 2>/dev/null
    ;;
  "eww"    )
    echo Loading eww
    echo TODO
    exit 0
    ;;
  *        )
    echo No such bar
    echo Bars: polybar, eww
    exit 0
    ;;
esac


sleep 1

echo Setting wallpaper...
WPFILE=`ls $HOME/wps/$NEW | sort | head -n 1`
nitrogen --set-auto $HOME/wps/$NEW/$WPFILE >/dev/null 2>/dev/null

echo Refreshing qtile...
pkill -SIGUSR1 qtile

echo Themeing nvim...
pkill -SIGUSR1 nvim

echo Themeing kitty
case "$NEW" in
  "latte")
    kitten theme catppuccin-latte 
    SPICETIFY="latte"
    VENCORD='@import url("https://catppuccin.github.io/discord/dist/catppuccin-latte.theme.css");'
    ;;
  "frappe" )
    kitten theme catppuccin-frappe
    SPICETIFY="frappe"
    VENCORD='@import url("https://catppuccin.github.io/discord/dist/catppuccin-frappe-lavender.theme.css");'
    ;;
esac

pkill -SIGUSR1 kitty

echo Themeing spotify...
spicetify config current_theme catppuccin >/dev/null
spicetify config color_scheme $SPICETIFY >/dev/null
spicetify config inject_css 1 inject_theme_js 1 replace_colors 1 overwrite_assets 1 >/dev/null
spicetify apply >/dev/null

echo Themeing discord...
echo $VENCORD > $HOME/.config/Vencord/themes/catppuccin-dynamic.css 

